# PyTorch
* site:https://pytorch.org/
* PyTorch is an open source machine learning framework based on the Torch library<br>
>simiral concurent Tensorfllow: https://www.tensorflow.org/
### pros

* production ready
* distributed training(cpu,gpu,networking,cloud)
* flexible & robust 
* easy to begin with
* oop / function oriented


## torch tensor - teh CORE "package used to store data in PyTorch
<img src="img1.png" style="width:700px;height 700px"/>

## Let's try some operations with torch tensors
<img src="img2.png" style="width:500px;height 500px"/>

In [38]:
import torch

In [39]:
t1 = torch.tensor([
    [1.,2.,3.],
    [4.,5.,6.],
    [7.,8.,9.]
], requires_grad = True)

t2 = torch.tensor([1.],requires_grad = True)
print(t1)
print(t2)


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)
tensor([1.], requires_grad=True)


In [40]:
t3 = t1+t2
t3.backward(torch.tensor([
    [1.,0.,0.],
    [1.,0.,0.],
    [1.,0.,0.]
    ]))

print(t3)
print(t1.grad)
print(t2.grad)


tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], grad_fn=<AddBackward0>)
tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])
tensor([3.])
